version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: graphgl_postgres
    environment:
      - POSTGRES_DB=graphgl_db
      - POSTGRES_USER=graphgl_user
      - POSTGRES_PASSWORD=graphgl_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata_graphgl:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  pgdata_graphgl:
